### ISSUE TITLE
http service undefined

### ISSUE THREAD

**Issue by simonagren** [benbaran/adal-angular4#1]
Hey,
 
Tried your sample, and even updated to latest adal-angular-4.

In home.component i try to do a 
`this.http.get('apiuri...')`

But the private http: Adal4HTTPService is undefined.

Do you know why?

**Comment by mavrj** [comment]
The sample uses the factory provider pattern, but when you look carefully to the Adal4HTTPService code you will see that the factory never return any value.

adal-angular4 / src / adal4-http.service.ts (lines 24 to 26)
`static factory(http: Http, service: Adal4Service) { `
`    new Adal4HTTPService(http, service);`
` } `

The code should be changed the code to:

`static factory(http: Http, service: Adal4Service) { `
`     return new Adal4HTTPService(http, service);    `
`} `
 as a workaround you can update directly the js code in your node_module directory

adal-angular4 / dist / adal4-http.service.js (lines 39 to 41)

` Adal4HTTPService.factory = function (http, service) {`
`        new Adal4HTTPService_1(http, service);`
`};`


to 
`Adal4HTTPService.factory = function (http, service) {` 
`        return new Adal4HTTPService_1(http, service); `
`}; `

I hope this helps

**Comment by simonagren** [comment]
Yeah, it helped!
Thanks :)

**Comment by benbaran** [comment]
This has been fixed in version 0.1.4. Thank you for the feedback!
