### ISSUE TITLE
Azure B2C AD

### ISSUE THREAD

**Issue by joakimlundvall** [benbaran/adal-angular4#11]
Hi Ben,

I had some troubles making this work with Azure B2C AD, with this change to the config all works as expected. Especially the logout was troubling. 

```typescript
const config = {
  tenant: environment.tenant,
  clientId: environment.clientId,
  extraQueryParameter: '',
  logOutUri: ''
};


  constructor(private service: Adal4Service,
    private http: Adal4HTTPService) {
   
	
    config.logOutUri = 'https://login.microsoftonline.com/' + environment.tenant + '/oauth2/logout?post_logout_redirect_uri=' +
      encodeURIComponent(window.location.href.split('?')[0].split('#')[0]) + '&' +
      'p=' + environment.profile;

    config.extraQueryParameter = 'p=' + environment.profile + '&scope=openid';

    this.service.init(config);
  }
```

**Comment by benbaran** [comment]
Thank you for your feedback. I will incorporate into the next version when I have time to test.

**Comment by benbaran** [comment]
For B2C, I would suggest you use the msal-angular library.

**Comment by joakimlundvall** [comment]
Thank you Ben,

I will look into it.

Joakim Lundvall
Verksamhetskonsult
[logo2016web]<http://traventus.se/>

Direkt: 010-410 46 12
E-post: joakim.lundvall@traventus.se<mailto:joakim.lundvall@traventus.se>

Växel 010-410 46 00 / Support 010-410 46 01
Yxhammarsgatan 8-10, 50431 Borås

Visma Business<http://www.traventus.se/vara-losningar/visma-business/> – Visma Administration<http://www.traventus.se/vara-losningar/visma-administration/> – Visma.NET<http://www.traventus.se/vara-losningar/visma-net/>

[cid:image002.png@01D1C7D8.EDDAFC30]<https://www.facebook.com/traventus>[cid:image003.png@01D1C7D8.EDDAFC30]<http://www.linkedin.com/company/traventus-ab>
