### ISSUE TITLE
Opening page in new tab triggers loging

### ISSUE THREAD

**Issue by jrmcdona** [benbaran/adal-angular4#118]
I can successfully login and navigate.  If I right click a link and open it in new tab,  it tries to login again.  The token is not expired it just doesn't seem to get the token when specifically opening in a new tab.

Any ideas?

**Comment by terracott** [comment]
Hi. By default library use sessionStorage as token storage. It is not shared beetween tabs. You can set localStorage as cacheLocation parameter. It resolve this problem.

**Comment by jrmcdona** [comment]
correct!
