### ISSUE TITLE
Cannot find module 'adal-angular'

### ISSUE THREAD

**Issue by woodm1** [benbaran/adal-angular4#12]
Getting the following error on ng serve:

ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/adal4.service.d.ts (3,22): Cannot find module 'adal-angular'.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//src/backends/browser_jsonp.d.ts (1,33): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//src/errors.d.ts (9,33): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//src/errors.d.ts (10,43): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//src/errors.d.ts (11,42): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//src/errors.d.ts (12,43): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//src/errors.d.ts (13,35): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//src/animation/dsl.d.ts (81,33): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//src/animation/animation_metadata_wrapped.d.ts (12,33): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//http/src/jsonp.d.ts (5,44): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//http/src/jsonp.d.ts (6,45): Initializers are not allowed in ambient contexts.
ERROR in C:/Users/Matt/Source/Repos/internal/node_modules/adal-angular4/node_modules//http/src/jsonp.d.ts (7,52): Initializers are not allowed in ambient contexts.

Using latest Angular-CLI version. I've tried the fixes suggested at alenny/angular2-adal#8 but they're for the Angular 2 version, and no luck.

Any ideas?

**Comment by benbaran** [comment]
This has been fixed in the v2 library.
