### ISSUE TITLE
Unable to fetch Roles defined in Application Manifest

### ISSUE THREAD

**Issue by shashidharshridhar** [benbaran/adal-angular4#13]
Hi Ben, 
         I am using adal-angular4 for authenticating my Application against Azure AD. I am able to succeed in Authentication. However when I tried to Authorize my Angular Components using the Roles defined in Azure Manifest I am not able to get the same. Can you please guide me how can I resolve the issue.
      Please find the data present in the UserInfo below.
{
    "aud": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "iss": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "iat": 1506085285,
    "nbf": 1506085285,
    "exp": 1506089185,
    "aio": "ATQAy/8FAAAA/WMobpsABxDXJ4gCPGFyk6p39T703tWKOPTaevFDhpQdcbyBdFA2+R4pZaz2ro63",
    "amr": [
        "pwd"
    ],
    "email": "xxxxxxxxxxxx@xxxx.onmicrosoft.com",
    "family_name": "xxxxxxxx",
    "given_name": "xxxxxxxxxxxx@xxx.onmicrosoft.com",
    "groups": [
        "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    ],
    "idp": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx/",
    "ipaddr": "x.x.x.x",
    "name": "xxxx@xxxxx.onmicrosoft.com",
    "nonce": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "oid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "sub": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "tid": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
    "unique_name": "xxxxxxx@xxxxxx.onmicrosoft.com",
    "ver": "1.0"
}

I am expecting Roles which we have defined in the Manifest file. Can you please let me know whether my understanding is right regarding the roles that need to be present in the **userInfo.profile** and can I know is there any API reference for the same.. 
Please find the details of manifest file below.

"appId": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
  "appRoles": [
    {
      "allowedMemberTypes": [
        "User"
      ],
      "displayName": "Owner",
      "id": "fc1fc18a-e366-4257-be5e-e495c339fe64",
      "isEnabled": true,
      "description": "Owner can manage roles and perform all task actions.",
      "value": "Owner"
    },
    {
      "allowedMemberTypes": [
        "User"
      ],
      "displayName": "Reader",
      "id": "4881ec9c-d4b1-4e14-b4c0-33fdd48b4cb5",
      "isEnabled": true,
      "description": "Reader only have the ability to view tasks and their statuses.",
      "value": "Reader"
    }
  ]

Thanks, 
Shashi

**Comment by shashidharshridhar** [comment]
Hi Ben,
         I was able to resolve the issue. I had to create groups and assign roles. Hence closing the bug.
Thanks,
Shashi

**Comment by chrisedg87** [comment]
Realise this is old but I'm having the same issue. My manifest looks similar to yours but I'm not getting the groups returned in my token. Is there something additional you have to configure in the adal config? How did you get around this?
