### ISSUE TITLE
Loop back

### ISSUE THREAD

**Issue by faheemfactor** [benbaran/adal-angular4#14]
Hi ,

Your library works very fine.  
If end user haven`t specified the return url. Library finds the current page url and  assign as return and logout url.
However for application registered in the Azure Directory requires redirect url  and which incorporated in jwt.
PROBLEM
if application base URL : http://localhost:4200/  and end user got unauthenticated for any reason while at specific page of application http://localhost:4200/admin/usersettings. The library parse this URL. which required to be registered at Azure AD portal application as return url. 
To avoid multiple return url it would be great to pass the only origin url only.
Fix :
file : adal4.service.ts
let pathDefault = configOptions.authenticatedUri || (window.location.origin + '/');
configOptions.postLogoutRedirectUri = configOptions.postLogoutRedirectUri || pathDefault + '/logout';

this will work for us to  save from registering multiple urls of application in Azure AD portal.

**Comment by leonixyz** [comment]
Hi, have you tried using a wildcard reply url in Azure portal? 

http://paulryan.com.au/2016/azure-ad-app-wildcard-reply-url/

**Comment by geerzo** [comment]
I'm closing due to how old this is without a response from the original poster to the suggested fix.
