### ISSUE TITLE
How to Use AdalGuard

### ISSUE THREAD

**Issue by Milan03** [benbaran/adal-angular4#140]
How is the provided guard meant to be used? If I add it, it blocks the guarded routes but doesn't redirect anywhere to login (app just sits at the base URL). Here is my routes.ts:

    export const routes = [

    {
        path: '',
        component: LayoutComponent,
        canActivate: [AdalGuard],
        children: [
            { path: '', redirectTo: 'home', pathMatch: 'full' },
            { path: 'home', loadChildren: './home/home.module#HomeModule' },
            { path: 'display', loadChildren: './display/display.module#DisplayModule' },
            { path: 'inbox', loadChildren: './inbox/inbox.module#InboxModule' },
            { path: 'maintenance', loadChildren: './maintenance/maintenance.module#MaintenanceModule' }
        ]
    },

    { path: 'auth-callback', component: AuthCallbackComponent },
    { path: 'login', component: LoginComponent },
    { path: 'logout', component: LogoutComponent },

    // Not found
    { path: '**', redirectTo: 'login' }

    ];

Can I configure a path to redirect to login component?

**Comment by benbaran** [comment]
You may just want to implement your own guard with that feature. Here is an example:

https://juristr.com/blog/2018/11/better-route-guard-redirects/
