### ISSUE TITLE
page reload when removing hash from uri in handlewindowcallback

### ISSUE THREAD

**Issue by BartNetJS** [benbaran/adal-angular4#16]
in the handlewindowcallback(adal4.service.ts) the hash with token is removed from the uri (as expected).
But my page (or token renew in iframe) is reloaded after
> window.location.href = window.location.href.replace(window.location.hash, ''); 

my basic route is 
> { path: '', redirectTo: '/home', pathMatch: 'full' }

i'm using PathLocationStrategy (the default)

any idea?

**Comment by charlesrey** [comment]
I have the same issue with the same configuration (root route redirect to home) and wiil be glad to find a solution.

Thanks.

**Comment by BartNetJS** [comment]
The following did the trick. Changing the history state, so the browser doesn't see the url change.
Another interesting side effect is, when you go back via the browser, you don't see the previous url with the hash, but the real previous route

in adal4.service.js(handleWindowCallback) I changed the remove hash logic with:
> if (window.location.hash) {
>            if (window.history.replaceState) {
 >               window.history.replaceState('', '/', window.location.pathname)
 >           } else {
 >               window.location.hash = '';
 >           }
 >}

@charlesrey can you confirm if this also work in your code.
If so, I will create a pull request

**Comment by mitch-b** [comment]
@BartNetJS - I found this issue after I had already made the same change myself ... now I checked to see if anyone else had the need for better handling after callback.

I have had good behavior with this change. Go for the pull request!

**Comment by ollief87** [comment]
This change seems to fix the redirect issue for me. Can you do the pull request?

**Comment by mikerains** [comment]
I have the same experience here, and the code change contributed by BartNetJS does resolve the issue.   I vote for the Pull Request as well.

**Comment by ollief87** [comment]
@BartNetJS can you do the PR with the change? If not I can do a PR with your change

**Comment by benbaran** [comment]
This change has been merged : )
