### ISSUE TITLE
Adal4-http.service always appends the Bearer token header

### ISSUE THREAD

**Issue by jonbran** [benbaran/adal-angular4#17]
The Bearer token is always appended even if the Bearer token header already exists. This can cause the first request to succeed but subsequent requests to fail.

Line 158 (i think) could be changed from
options1.headers.append('Authorization', 'Bearer ' + token);
To
options1.headers.set('Authorization', 'Bearer ' + token);

That resolved the issue for me but it will break if I ever do an update so I hope to see it fixed here.

**Comment by subhankar99** [comment]
Use https://www.npmjs.com/package/adal-angular4plus -- This is compatible with latest version of angular 5.0.0 and ng CLI. Also your reported bug is fixed in this

**Comment by chrisjau** [comment]
Work around is to have the api on a different domain to the angular app.  Can someone look into this, it's been an issue for quite a while.

**Comment by geerzo** [comment]
What version are you seeing this on?

**Comment by geerzo** [comment]
Closing due to age and no response.
