### ISSUE TITLE
handleWindowCallback() doesn't renew id_token

### ISSUE THREAD

**Issue by eKipod** [benbaran/adal-angular4#18]
In `handleWindowCallback`, if renew succeeds for anything but `'access_token'`, nothing happens (leaving e.g. `acquireToken()` hanging).
Should there be a case for handling `'id_token'`?
Should there be a catch-all error callback invocation?

**Comment by alan-g-chen** [comment]
I ran into the same issue, and have submitted a PR to fix it.

**Comment by geerzo** [comment]
Closing as an old issue that appears to have been solved. Please post a new issue if there is still an issue here.
