### ISSUE TITLE
missing adal.Config

### ISSUE THREAD

**Issue by joakimja** [benbaran/adal-angular4#19]
I liked your project and see the goodness in it.
 But I needed to change in the adal4.service.d.ts
from "adal.Config" to "any". And then I got it to work.

The issue i got was
adal-angular4/adal4.service.d.ts (48,27): Namespace ''*'' has no exported member 'Config'.

I use
adal-angular -version 1.0.15
adal-angular4 -verison 1.1.10

`constructor();
    /**
     *
     *
     * @param {adal.Config} configOptions
     *
     * @memberOf Adal4Service
     */
    init(configOptions: adal.Config): void;
    /**
     *
     *
     * @readonly
     * @type {adal.Config}
     * @memberOf Adal4Service
     */
    readonly config: adal.Config;

**to**

constructor();
    /**
     *
     *
     * @param {adal.Config} configOptions
     *
     * @memberOf Adal4Service
     */
    init(configOptions: any): void;
    /**
     *
     *
     * @readonly
     * @type {adal.Config}
     * @memberOf Adal4Service
     */
    readonly config: any; `

**Comment by geerzo** [comment]
I'm closing this as it's an old issue. If this is still an issue for anyone please reopen it with how to reproduce.
