### ISSUE TITLE
JWT token not included in call to Web API

### ISSUE THREAD

**Issue by ljayaprakash** [benbaran/adal-angular4#2]
Hello benbaran,
I'm trying to access web api using http call, for some reason request is not including authentication value in headers section (jwt token received from Azure in my case). Web API returning 401 - unauthorized.
Do I need to save jwt token to local storage after authentication?
Do you have any sample code on this?

Request:
    getLocation(): Observable<any> {
        return this.http
            .get(`https://localhost:44383/api/location?cityName=stl`)
            .map((response: Response) => response)
            .catch(this.handleError);
    }

**Comment by benbaran** [comment]
You would want to use the Adal4HTTPService included. I have not tested it to be honest. Otherwise, you should be able to retrieve the token from the Adal4Service and send it in the request headers with a RequestOptions object.

**Comment by ljayaprakash** [comment]
I did try passing header in RequestOptions object but no luck. 
After further investigation, looks like JWT token missing some values.
"appid" - <<no entry for this property>> (It should be client id from app registration)
"aud" - <<app_id>> (this should be _http://someone.onmicrosoft.com/CortanaWebAPI_ instead of app_id)

**Comment by BartNetJS** [comment]
I also added specific the RequestOptions, but created also an empty Header object in the RequestOptions object, and things started to work.
The authorization header was added

**Comment by benbaran** [comment]
This has been fixed in the v2 library.
