### ISSUE TITLE
Http is deprecated 

### ISSUE THREAD

**Issue by Hopchenko** [benbaran/adal-angular4#20]
Hello, could you please add HttpClient support to your awesome lib?
Because for now http is deprecated in angular 5

**Comment by stas-kh** [comment]
Yes, we are really waiting for this change.
It will also allow to upgrade the project to Angular 5

**Comment by davemcmanus** [comment]
Are there any plans to update to HttpClient?

**Comment by geerzo** [comment]
I'm closing this as it's an old issue. If this is still an issue for anyone please reopen it with how to reproduce.
