### ISSUE TITLE
Angular 5 ?

### ISSUE THREAD

**Issue by cannehag** [benbaran/adal-angular4#25]
Are there any plans for support angular 5 ? (perhaps in a new project)

**Comment by Codefearingguy** [comment]
Looks like there is no ADAL wrapper available so far which supports angular5.

**Comment by subhankar99** [comment]
Use https://www.npmjs.com/package/adal-angular4plus -- This is compatible with latest version of angular 5.0.0 and ng CLI

**Comment by Codefearingguy** [comment]
i have used ng2-adal, I got it working with Angular5 with AOT

**Comment by leonixyz** [comment]
I am currently using this library with angular5 in a number of projects, it works fine
