### ISSUE TITLE
Is this still maintained?

### ISSUE THREAD

**Issue by Brototype** [benbaran/adal-angular4#27]
I see some issues related to angular 5 without response. If this repo is no longer maintained and there are no plans to migrate to angular 5 maybe we should fork it. Anyone interested in this?

**Comment by almatty** [comment]
I'd be interested in a fork. This was working nicely for Angular 4, and I've love to be able to use it in a new project.

**Comment by bradsavon** [comment]
https://github.com/grumar/adal-angular5
