### ISSUE TITLE
How do we use it in systemjs?

### ISSUE THREAD

**Issue by jayeshvg** [benbaran/adal-angular4#3]
No umd file. Using index.js file gives adal-angular4/adal4-user not found.
Similarly adal-angular4/adal4.service not found, and also adal4-http.service not found.

I have  added  'adal-angular4': {
                defaultExtension: 'js'
            }, to systemjs.

 'adal-angular4': 'npm:adal-angular4',
            'adal-angular': 'npm:adal-angular',

in map folder

**Comment by egalitarian11** [comment]
@jayeshvg Also struggling with this. Did you have any luck?

**Comment by jayeshvg** [comment]
Following worked for me:

In map: 
```
'adal-angular4': 'npm:adal-angular4',
            'adal': 'npm:adal-angular/lib',
            'adal-angular': 'npm:adal-angular/lib',
```

In Packages: 

```
'adal-angular4': { main: 'index.js', defaultExtension: 'js' },
            'adal-angular': { main: 'adal-angular', defaultExtension: 'js' },
            'adal': { main: 'adal.js', defaultExtension: 'js' },
```



npm is common path for node_modules files

**Comment by geerzo** [comment]
Closing as a solution was posted.
