### ISSUE TITLE
I can't get acquireToken to work.

### ISSUE THREAD

**Issue by kov-hans** [benbaran/adal-angular4#32]
When acquireToken is called, the renew state is stored in the context object in the AdalService instance, but when the token is received and I call handleWindowCallback the context in the AdalService doesn't contain any renew states. If I call acquireToken again I can see that the previous renew state is still in the context. My conclusion is that for some reason there are different instances of the context object in the AdalService. I have added AdalService as a provider in the app-module.ts so there should only be one instance of the AdalService but can there still be several instances of the context object inside of the AdalService? Am I doing something wrong or have I ran into a bug? I'm using the latest 2.x.x version. I should also mention that when I ran adal-angular4 with version 1.0.15 of adal-angular it all worked fine. I saw a code difference in adal-angular that I reported as a bug (https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/712) but the issues was closed with the reply that adal-angular4 had to be updated!

**Comment by mariiaBilyk** [comment]
I have exactly the same issue with adal-angular4 v 1.1.11.
We haven't updated our sources since December 2017, seems like you have some regression.
I can retrieve an access token for resource manually, using /common/oauth2/v2.0/token endpoint. 
Why wouldn't you update this library to work with the latest Azure AD endpoints?
https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-v2-protocols-oauth-client-creds#get-a-token

![image](https://user-images.githubusercontent.com/11858336/36729136-ccf6c55a-1bcb-11e8-9913-7f2f5db7fe3e.png)

**Comment by MarkusFalgenhauer** [comment]
The issue is definetly a problem with adal.js 1.0.16 as mentioned from kov-hans.
With adal-angular4 v 1.1.11 and adal.js 1.0.16 the access_token is not stored
with adal.js 1.0.15 it works fine.

Is there a possibility to fix that in adal-angular4?

**Comment by kov-hans** [comment]
I have also asked for help from the adal.js team to locate the problem.
https://github.com/AzureAD/azure-activedirectory-library-for-js/issues/718

**Comment by JoshSchoen** [comment]
For what it's worth I found this repo https://github.com/AlexeyBoiko/angular5-office365-adal-example  works with angular 5.2.0 acquireToken() works as expected. For me it removes the need for this library and seems to be a good start to working with adal.js directly.

**Comment by web265p3** [comment]
Same issue here. I had to got back to version 1.0.15 to get acquireToken to work.

**Comment by benbaran** [comment]
The adal-angular version has been set back to the working version. I will update to the newest version once that bug is fixed : )
