### ISSUE TITLE
Username always undefined

### ISSUE THREAD

**Issue by petinho** [benbaran/adal-angular4#35]
After login I'm receiving the username as undefined.

Debugging I've seen that the variable is wrong in the updateDataFromCache function:
`
if (user) {
            this.user.username = user.username;
            this.user.profile = user.profile;
            this.user.token = token;
            this.user.error = this.context.getLoginError();
        }`
I've changed it to (notice capital N):

`this.user.username = user.userName;`

Am I right?

**Comment by stuarthallows** [comment]
I've put in a pull request to fix this.

**Comment by mikerains** [comment]
I find the same condition and vote for this Pull Request.

**Comment by benbaran** [comment]
The pull request fixing this has been merged : )
