### ISSUE TITLE
Generated token is not authorizing API.

### ISSUE THREAD

**Issue by RasikaMK** [benbaran/adal-angular4#39]
After generating token from my code, when I post the token in Postman header along with my api url in url section and GET request , I am getting below message :
{
    "Message": "Authorization has been denied for this request."
}

Please suggest me some solution.

**Comment by leonixyz** [comment]
can you provide more details, e.g. can you paste your code and the http request you are issuing in postman?

**Comment by geerzo** [comment]
Closing due to lack of response. Please provide more information if it's still an issue.
