### ISSUE TITLE
Angular 6

### ISSUE THREAD

**Issue by rjwijnen** [benbaran/adal-angular4#41]
With the release of Angular 6 i get the warning:

npm WARN adal-angular4@2.0.15 requires a peer of @angular/common@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN adal-angular4@2.0.15 requires a peer of @angular/core@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN adal-angular4@2.0.15 requires a peer of @angular/platform-browser@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN adal-angular4@2.0.15 requires a peer of @angular/router@^5.2.5 but none is installed. You must install peer dependencies yourself.
npm WARN adal-angular4@2.0.15 requires a peer of rxjs@^5.5.6 but none is installed. You must install peer dependencies yourself.

Maybe update the packages and files to support Angular 6?

**Comment by benbaran** [comment]
The package has been updated to support Angular 6 in the 3.x version.

**Comment by kaburkett** [comment]
Thanks for maintaining the project. I've confirmed 3.x is working with angular 6... had to actually switch packages from adal-angular5 to this package since this one is the one that's actually maintained
