### ISSUE TITLE
Documentation or example required

### ISSUE THREAD

**Issue by HighSoftWare96** [benbaran/adal-angular4#44]
I think that it would be nice if some documentation or examples was provided.

**Comment by geerzo** [comment]
https://github.com/benbaran/adal-angular4-example

**Comment by frompedro** [comment]
Hello geerzo, i am using adal-angular 4 to connect to Azure AD and then to Graph API. can you provide an example on how to call a graph api endpoint?

Can you help please?
![image](https://user-images.githubusercontent.com/3612786/41218320-fb9b5714-6d5a-11e8-901d-aeb0ffcd848f.png)
