### ISSUE TITLE
Acquire Token does not renew token 

### ISSUE THREAD

**Issue by JayeshLunkad** [benbaran/adal-angular4#48]
Hi,
I have configured AD in my angular 5 web app. It returns the token and stores it in session storage. But I want to renew the token before it expires. so I call acquiretoken() before expiry time but it doesn't renew the token. It returns the same token each time called. Can you please help how can i renew the token silently even if my page is idle.

Thanks,
Jayesh

**Comment by kingdomflo** [comment]
I have the same problem
I have read in some blog or stackoverflow issus that acquireToken look if we have a right cookie (and if not, it doesnt refresh), but... I don't see cookie in my local storage, I never see cookie created

Is it that the problem?

**Comment by FrankyHuQingFeng** [comment]
in the config settings using:     cacheLocation: 'localStorage',

**Comment by geerzo** [comment]
By default, the adal system will automatically renew the token when you call acquireToken if it has expired. You shouldn't cache the token yourself, you should allow the tool to do it. If you are using the interceptor you shouldn't have to care about the token at all.

**Comment by geerzo** [comment]
I'm going to close due to no continued discussion. Feel free to reopen if required.

**Comment by cindymarie** [comment]
I have the same issue. :(
