### ISSUE TITLE
Add CORS

### ISSUE THREAD

**Issue by web265p3** [benbaran/adal-angular4#55]
In order to get this library to work with CORS, I always have to remove the "X-Requested-With" from my requests. The interceptor does not do this automatically, neither did I find a way how to configure it. 

https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/CORS-usage

Is there a way how I can configure adal-angular4 to be CORS-ready?

**Comment by DanaEpp** [comment]
Did you find a way around the CORS issue?

**Comment by web265p3** [comment]
Nope - I still remove the Header. But that works...

**Comment by geerzo** [comment]
@web265p3 Are you using the endpoints mechanic as they mention in that post you linked? If you take a look at the [example project](https://github.com/benbaran/adal-angular6-example) it now calls the GraphAPI and doesn't have any CORS issues.

**Comment by geerzo** [comment]
I'm closing this since it's old and no response in over a month. Feel free to reopen if there is still an issue.
