### ISSUE TITLE
adal.Config missing logOutUri

### ISSUE THREAD

**Issue by JasonPaape** [benbaran/adal-angular4#57]
The type definition for the config object is missing the logOutUri property.
https://github.com/benbaran/adal-angular4/blob/master/adal-angular.d.ts

declare namespace adal
...
interface Config {
...
logOutUri?: string;  // <-- missing

Can you add it please? I got around it by typing my apps adal config object to "any" for now.

**Comment by geerzo** [comment]
This is added in ecf866607cd51b74727da38daba0b3c0d87a81ae
