### ISSUE TITLE
Unable to call secure WebApi

### ISSUE THREAD

**Issue by elena89rossi** [benbaran/adal-angular4#58]
I've update my app from angular4 to angular6, and now I'm unable to call secure web api.
I try to setup a PrepareOptions method to setup HttpHeaders
I have already try to use a PrepareOptions method to setup HttpHeaders but I've always HttpResponse "Unauthorized".
Here my code

import { Component, OnInit } from '';
import { AdalService } from 'adal-angular4';
import {HttpHeaders, HttpClient} from '/http';
import {environment} from '../../environments/environment';

@component({
selector: 'app-home',
templateUrl: './home.component.html',
styleUrls: ['./home.component.css']
})
export class HomeComponent implements OnInit {
activities:any;
constructor(private adalService: AdalService,private http:HttpClient) { }

ngOnInit() {
this.getActivities();
}

getActivities():any{
return this.http.get(${environment.apiUrl},this.prepareOptions())
.subscribe(res=>this.activities=res,error=>console.log(error))
}
private prepareOptions(): any {
let headers = new HttpHeaders();
       headers = headers
           .set('Content-Type', 'application/json;')
           .set('Accept', 'application/json;')
           .set('Authorization', `Bearer ` +` ${this.adalService.userInfo.token}`);
       return { headers };
}}.
If i try to use Http_interceptor without PrepareOption Method as a parameter of Http call, I've this error:
core.js:1601 ERROR Token renewal operation failed due to timeout:
app.module:

@NgModule({
declarations: [
AppComponent,
HomeComponent,
],
imports: [
BrowserModule,
AppRoutingModule,
BrowserAnimationsModule,
MaterialModule,
HttpClientModule
],
providers: [AdalService, AdalGuard,
{
provide: HTTP_INTERCEPTORS,
useClass: AdalInterceptor,
multi: true
},
ActivityService

]
,
bootstrap: [AppComponent]
})
export class AppModule { }

ACTIVITYSERVICE.TS
import { Injectable } from '';
import { AdalService } from 'adal-angular4';
import {HttpHeaders, HttpClient} from '/http';
import {environment} from '../environments/environment';

@Injectable({
providedIn: 'root'
})
export class ActivityService {
constructor(private http:HttpClient,private adalService:AdalService) { }
getActivities():any{
return this.http.get(${environment.apiUrl})
}
}

HOME.COMPONENT
this.activitiesService.getActivities().subscribe(res=>console.log(res));

can anyone help me?

**Comment by geerzo** [comment]
See this issue #49

**Comment by geerzo** [comment]
You need to downgrade adal-angular to 1.0.15 and change the package.json of adal-angular4 to use adal-angular 1.0.15.

**Comment by brettkc** [comment]
@elena89rossi  Changing nested dependencies see: https://stackoverflow.com/a/48524488/5670286

**Comment by magleahy** [comment]
https://www.npmjs.com/package/adal-angular6 is deprecated. 
"Warning: Deprecated!!!
Please use https://github.com/benbaran/adal-angular4 which has already been merged into angular 6.

This repository lives only as my personal documentation on how to do a naive migration."

**Comment by geerzo** [comment]
Please see the [Example Project](https://github.com/benbaran/adal-angular6-example) for a working example of calling the Graph API. Please use 3.0.5 of this library.
