### ISSUE TITLE
Wrong Audience in Bearer token

### ISSUE THREAD

**Issue by sonphnt** [benbaran/adal-angular4#60]
Hi,

I am having 2 projects (WebAPI .Net core 2.0 and Angular 6). they are hosted separately. I used to make this Azure AD authentication worked with Angular JS and .Net core 2.0 but no success with Angular 6.

I realize my token in Angular 6 has a wrong "Aud" value that's why I got "Wrong audience error exception".
In Angular 6: aud: "angular client id"
In AngularJS: aud "webapi app id URI"

Does anyone know why? 

Thanks very much

**Comment by ThomasPe** [comment]
We seem to be facing the same issue. Did you get anywhere with this yet?

**Comment by sonphnt** [comment]
I found a way by calling acquiretoken() in adal to get a real access token with resourceid.
```
  public acquireToken(): Observable<string> {
    return this._adal.acquireToken(environment.adalConfig.resourceId).pipe(map(token => token.toString()));
  }
```

**Comment by geerzo** [comment]
Is this still an issue? Do you have sample code somewhere to reproduce the issue?

**Comment by geerzo** [comment]
Closing due to lack of response.
