### ISSUE TITLE
Bearer error="invalid_token", error_description="The issuer is invalid"

### ISSUE THREAD

**Issue by daver77** [benbaran/adal-angular4#61]
Hi,

Has anyone successfully used the token from an Angular6 app against a .NET Core Web API? 

When I try I get the error 
**_WWW-Authenticate: Bearer error="invalid_token", error_description="The issuer is invalid"_**

In my Startup.cs I have:

```
            services.AddAuthentication(options =>
            {
                options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
                options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
            }).AddJwtBearer(options =>
            {
                options.Authority = "https://login.microsoftonline.com/common";
                options.Audience = "[application id]";
                options.TokenValidationParameters.ValidateLifetime = true;
                options.TokenValidationParameters.ClockSkew = TimeSpan.Zero;
            });

            services.AddAuthorization();
```

My API is

```
    [Authorize]
    [Route("api/[controller]")]
    public class ProjectController : Controller
    {
```

I can see that the bearer token is being passed to my API in the Authorization header

**Comment by daver77** [comment]
I decoded my token and noticed that "iss" was set to 

https://sts.windows.net/60e0ab8b-8c8d-4eef-b9c2-f9cb65535c28

so I set

`options.Authority = "https://sts.windows.net/60e0ab8b-8c8d-4eef-b9c2-f9cb65535c28";`

and now my API authenticates. I'm not sure where 60e0ab8b-8c8d-4eef-b9c2-f9cb65535c28 comes from though, anyone know?

**Comment by geerzo** [comment]
Check out [this blog](https://cloudblogs.microsoft.com/enterprisemobility/2015/03/06/simplifying-our-azure-ad-authentication-flows/). I looks like the endpoints changed to login.microsoftonline.com but the issuer stayed the same as sts.windows.net.

Let me know if I can close this issue.

**Comment by geerzo** [comment]
Closing due to lack of response and it looking like a non-issue.

**Comment by TracyGH** [comment]
Thank you, thank you, thank you!!!  I spent so many hours troubleshooting this issue.
@geerzo - Any chance we can get the documentation updated to reflect the correct issuer?
[https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/web-api](https://docs.microsoft.com/en-us/azure/architecture/multitenant-identity/web-api
)
