### ISSUE TITLE
correct usage of acquireToken

### ISSUE THREAD

**Issue by daver77** [benbaran/adal-angular4#62]
I'm trying to use acquireToken to get a token for the VSTS API using

```
        this.adal.init(environment.adalConfig);
        this.adal.acquireToken('499b84ac-1321-427f-aa17-267ca6975798')
            .subscribe(
                data => {
                    console.log(data);
                },
                error => console.log(error)
            );
```

but it doesn't seem to be doing anything. I can see the response in fiddler and it looks okay. Is the code above wrong?

I can get everything working fine using adal.js from the code at https://github.com/Microsoft/vsts-auth-samples/tree/master/JavascriptWebAppSample

**Comment by daver77** [comment]
I downgraded to adal-angular 1.0.14 and it now works

**Comment by DanaEpp** [comment]
Why did the downgrade work? Why didn't this work with the latest stuff?

**Comment by benbaran** [comment]
Someone mentioned it looked like a bug in the latest adal version. I have not had the opportunity to investigate myself, unfortunately. I don’t use this library myself, just a hobby project that has gained some traction...

**Comment by DanaEpp** [comment]
So @benbaran do you know what the right way is to silently call acquireToken and not have it redirect?

**Comment by daver77** [comment]
@DanaEpp - the above code works, just change the dependency to adal-angular 1.0.14.

[https://github.com/AzureAD/azure-activedirectory-library-for-js/blob/master/changelog.txt](You can see the change here). I'm guessing this had something to do with it

Version 1.0.15
=========================
* Added acquireTokenRedirect and acquireTokenPopup api's to acquire a token for resource interactively (MFA) and support conditional access.

**Comment by daver77** [comment]
I've got [@types/adal-angular](https://www.npmjs.com/package/@types/adal-angular) to work. [This helped](https://github.com/DefinitelyTyped/DefinitelyTyped/issues/12586).

```
import { Component, OnInit } from '@angular/core';
import * as AuthenticationContext from 'adal-angular';

// The AuthenticationContext needs to be globally available for adal-angular
window['AuthenticationContext'] = AuthenticationContext;

@Component({
  selector: 'app-auth2',
  templateUrl: './auth2.component.html',
  styleUrls: ['./auth2.component.css']
})
export class Auth2Component implements OnInit {

  private _context: AuthenticationContext;
  public token :string;

  constructor() { }

  ngOnInit() {
    let authContext = new AuthenticationContext (this.adalConfig());

    let isCallback = authContext.isCallback (window.location.hash);
    authContext.handleWindowCallback ();    

    this._context = authContext;
  }

  login() {
    this._context.login();
  }

  logout() {
    this._context.logOut();
  }

  getToken() {

    this._context.getCachedUser();
    this._context.acquireToken('499b84ac-1321-427f-aa17-267ca6975798', (error, token) => {

      console.log(error);
      console.log(token);

      this.token = token;

    });
  }

  private adalConfig(): any {
    return {
      tenant: 'xxx',
      clientId: 'xxx',
      postLogoutRedirectUri: window.location.origin
    };
  }

}
```

**Comment by daver77** [comment]
The bug is clearly somewhere within adal-angular4, I can call acquireToken on adal-angular 1.0.17 just fine when used with [@types/adal-angular](https://www.npmjs.com/package/@types/adal-angular)

**Comment by DanaEpp** [comment]
@daver77 I think you are on to something. Pointing to the changelog was a real help.

Look at the bullet in 1.0.16:

> * In the case where user already has an existing session with AAD and just wants to acquire a token for a resource for the same user using Adal, he can set  extraQueryParameter:'login_hint=xxx' in the adal config and
>   directly call acquireToken without calling login first. In this scenario, adal will send the request with responseType = 'id_token token' in a hidden iframe to receive both an id_token to estabilish user context 
>   as well as an access_token for the specified resource. 
>   This feature allows silent login as opposed to showing a UI in the case where the user has an existing session with AAD.

I think that might be the culprit. I am going to go make some changes to my code and see if that will work.

**Comment by geerzo** [comment]
@DanaEpp were you able to figure anything out here? When I was debugging before I found the hidden iFrame was the culprit as it caused the angular app to reload. The findings are in #49 but I've pasted them below.

> After you load an application and then call a secure API it calls the aquireToken method which registers a callback and then ADAL creates a hidden iFrame to get the authorization token. The problem that happens is that once that authorization call returns the main Angular app seems to reload which clears out the application state so when it processes the returned token it doesn't know what to do with it. You can see this in the handleCallback method where it can't determine what the callback is for and assumes its a login call and disregards the actual token for the web call. To fix it I think there needs to either be a change to the ADAL library to handle saving session scope the same way that the aquireTokenRedirect method does, or there needs to be a way to not cause the app to reload with the hidden iFrame gets a response.

**Comment by DanaEpp** [comment]
I had the same findings. The hidden iFrame is whats killing it. My solution was to use session state management with NGXS and store the info and do a hard windows.top.location.href to force the reload, then rehydrate all the state so it works. Ugly as sin, but guaranteed to work.

**Comment by geerzo** [comment]
@DanaEpp are you using adal-angular 1.0.17 still? If not, take a look at #71 and see if helps with any refresh issues you were having.

**Comment by geerzo** [comment]
We now support adal-angular 1.0.17+ with the 4.x release of the library.
