### ISSUE TITLE
npm audit vulnerabilities

### ISSUE THREAD

**Issue by vipero07** [benbaran/adal-angular4#65]
There are at least 8 audit issues with the current package available on NPM. The worst offenders are two High vulnerability issues found in http-proxy-agent that allow for Denial of Service attacks. The http-proxy-agent library has been patched to version 2.2.0 to fix these known vulnerabilities. It would be worthwhile to update the package dependencies to their latest versions.

**Comment by benbaran** [comment]
New version published today with updated dependencies : )
