### ISSUE TITLE
Unable to access secured web api

### ISSUE THREAD

**Issue by satheeshdiva** [benbaran/adal-angular4#66]
Not able to Access the secured web api
keep getting Not authorized error even though i am passing the bearer token in the request

**Comment by DanaEpp** [comment]
Have you confirmed that the bearer token is correct? Use postman and directly send a GET request to your secured web API and inserting the bearer token. If its successful you should be able to determine that.

If its not, then can you look deeper into the message coming back from Azure AD and let us know the error you are getting?

**Comment by geerzo** [comment]
Please see the [Example Project](https://github.com/benbaran/adal-angular6-example) for a working example of calling the Graph API.
