### ISSUE TITLE
Will 3.0.6 will published to NPM?

### ISSUE THREAD

**Issue by nickraphael** [benbaran/adal-angular4#67]

**Comment by geerzo** [comment]
Even though NPM says 3.0.5 it appears to have the correct version of adal-angular (1.0.15).

```
 keywords: [ 'ADAL', 'Angular' ],
  repository:
   { type: 'git',
     url: 'git+https://github.com/benbaran/adal-angular4.git' },
  author: 'Ben Baran',
  bugs: { url: 'https://github.com/benbaran/adal-angular4/issues' },
  license: 'MIT',
  readmeFilename: '',
  version: '3.0.5',
  main: 'index.js',
  peerDependencies: {},
  dependencies: { 'adal-angular': '=1.0.15', npm: '6.1.0' },
```

**Comment by benbaran** [comment]
Hi Chris,

I see that you follow this package quite closely. Unfortunately it’s a hobby for me and I don’t have as much time to maintain it as I’d like. I be glad to add you as a comaintainer if you’re interested : )

**Comment by geerzo** [comment]
I'd be happy to help as much as I can. Can you add me here and for the example project?

**Comment by DanaEpp** [comment]
I'd be happy to help contribute too ben if you are open to pull requests.

**Comment by geerzo** [comment]
@benbaran any news on becoming a committer?

**Comment by benbaran** [comment]
Finally figured it out. You should get an invite.
