### ISSUE TITLE
Wrong timer interval in loginRefreshTimer 

### ISSUE THREAD

**Issue by simon11196** [benbaran/adal-angular4#73]
You calculate the interval with '**exp - this.now() - 300**' which are _seconds_.
But the rxjs timer requires _milliseconds_ as interval time.

`this.loginRefreshTimer = timer(exp - this.now() - 300).subscribe((x) => {
                this.refreshLoginToken()
            });`

In my example the token expires in ~37000 seconds but the timer is triggered every ~37 seconds
![image](https://user-images.githubusercontent.com/21359517/44207173-8aa60780-a15c-11e8-8716-eb9ad80f4446.png)

So i think it should be something like this: 
`this.loginRefreshTimer = timer((exp - this.now() - 300) * 1000).subscribe((x) => {
                this.refreshLoginToken()
            });`

**Comment by geerzo** [comment]
Good catch. I'll fix this.

**Comment by geerzo** [comment]
This is fixed in ecf866607cd51b74727da38daba0b3c0d87a81ae
