### ISSUE TITLE
not working with ngx-translate when user is not logged in

### ISSUE THREAD

**Issue by ursmeier-mercatus** [benbaran/adal-angular4#77]
I have troubles running ngx-translate with 3.0.7 of adal-angular4. I believe there is an issue with http interceptor.
- ngx-translate uses a HttpClient Loader for a local file
`TranslateHttpLoader(http, './assets/i18n/', '.json');`
-adal-interceptor get the clientId back and resource is filled (!!resource)
`const resource = this.adal.getResourceForEndpoint(request.url);
 if (!resource) {`
-the client is not yet logged in and the resource is not loaded
`if (!this.adal.userInfo.authenticated) {
            throw new Error('Cannot send request to registered endpoint if the user is not authenticated.');
        }`

If I understand the problem correctly the interceptor should not even add the authorization header in this case and just pass the request on. In no way it should cancel the request.

Has anyone adal-angular and ngx-translate running together or is it a bug?
Thanks.

**Comment by geerzo** [comment]
I'm not familiar with ngx-translator. Do you have sample code somewhere that reproduces the problem?

**Comment by ursmeier-mercatus** [comment]
ngx-translator uses a httpLoader, e.g.
```
export function createTranslateLoader(http: HttpClient) {
return new TranslateHttpLoader(http, './assets/i18n/,'.json');
}
```

which is then provided in the module. This loads the translation file via a http-call to the localhost.


I could solve (or workaround?) the problem by configuring adal with anonnymousEndpoints, e..g

```adalConfig: {
tenant:....,
clientId:....,
anonymousEndpoints: ['./assets'],
redirectUri: ….
}```

Not sure if the annymousEndpoints are meant for this, but I think that this solution is good enough. 
Closing the issue and thank you for looking into it and for adal-angular4.
