### ISSUE TITLE
npm dependency

### ISSUE THREAD

**Issue by yura-stepura** [benbaran/adal-angular4#78]
I noticed that in version v.2.0.15, `npm` was added to the list of dependencies together with `adal-angular`. And latest version of your library still have that dependency.

Having `npm ` in the dependency list causes a problem for us.
We use `license-checker` (https://www.npmjs.com/package/license-checker)  tool to keep track on licenses used in the project. It is used to check that no packages were added by developers on the team with licenses in the list that are not suitable for closed-source commercial project.

We run it using
`license-checker --summary --production`
But since we have your `adal-angular4` lib that adds `npm`, that license-checker tool reports all `npm` dependency licenses too. And there are number of those that are not suitable for closed-source commercial project on production ( e.g. Affero GPL )

I understand that was done simply to make sure that proper version of npm is installed on environments that use your lib. So in fact it is not dependency but devDependency.

Can you move that `npm` to the devDependencies or remove it completely?
Will appreciate your feedback so we can plan if to wait for lib update or to fork the lib.

**Comment by benbaran** [comment]
I don’t see a reason why not. I’ll take a look.

**Comment by yura-stepura** [comment]
Great. Thank you.
Let me know if you need additional info or anything else from me.

**Comment by benbaran** [comment]
The newest version removes the non dependency: )

**Comment by geerzo** [comment]
I'll close this as resolved. Let me know if it needs to be reopened.
