### ISSUE TITLE
Update adal-angular dependency?

### ISSUE THREAD

**Issue by jo-me** [benbaran/adal-angular4#80]
Hi,

is there a reason that version 1.0.15 of the adal-angular library is still used as a dependency?
The current version is 1.0.17. 

I moved from adal-angular5 to adal-angular4 after upgrading my app from Angular 5 to 6 and I'm seeing strange issues again like an occasional login loop. 
adal-angular5 is using 1.0.16 so maybe this was fixed already..

Thanks

**Comment by jo-me** [comment]
I see,  then it's strange why it works with adal-angular5 . I had no problems with it.
I'm currently experimenting with switching to 1.0.16 via some npm hacks to see whether my login loops are gone then. But npm is not really designed to fiddle with dependencies of dependencies..

Did you also try 1.0.17?

**Comment by jo-me** [comment]
Thanks to the recent update frenzy of adal-angular4 I'm now on 3.0.10 with adal-angular on 1.0.17 and without doing any cruel npm hacks :)

I originally also had issues refreshing tokens in the background with this adal-angular version, but after using the solution from the other thread (https://github.com/benbaran/adal-angular4/issues/84#issuecomment-418086607) it looks fine. maybe it's worth investigating it with more test cases as I'm currently only accessing APIs on the same domain.

**Comment by geerzo** [comment]
Version 4.x of this library now support adal.js 1.0.16+
