### ISSUE TITLE
Error during typscript compilation in latest version (3.0.9)

### ISSUE THREAD

**Issue by kameelyan** [benbaran/adal-angular4#81]
ERROR in ./node_modules/adal-angular4/index.ts
Module build failed: Error: \node_modules\adal-angular4\index.ts is missing from the TypeScript compilation. 

We had "^3.0.7" in our package.json and then as of this morning this error started occurring when 3.0.9 was pushed.

**Comment by brentbynum** [comment]
We've run into the same issue-- the compiled javascript files (adal.guard.js, adal.service.js, etc) aren't included in the package.

**Comment by benbaran** [comment]
My bad. Not sure what happened with the publish, but I’ll fix it tomorrow.

**Comment by benbaran** [comment]
I published a new version and it works with the example project. I’m hoping the issue has been resolved.
