### ISSUE TITLE
Relationship to sureshahal/angular2-adal

### ISSUE THREAD

**Issue by aciccarello** [benbaran/adal-angular4#9]
Hello, I'm evaluating adal libraries for Angular and it looks like this was derived from [sureshchahal/angular2-adal](https://github.com/sureshchahal/angular2-adal). Do you have a plan for including updates from that repo? Also, any reason that this isn't explicitly mentioned?

**Comment by LastTribunal** [comment]
If you don't want to have problems, stay away from this POS "library"

**Comment by aciccarello** [comment]
@LastTribunal I found your comments, including #8, excessively negative. You may be frustrated by your experience and may be correct that it is easier to create your own wrapper. If you have specific concerns it would helpful if you noted those as appropriate. However, I respect that the author has put his work out publicly and per the [MIT license](https://github.com/benbaran/adal-angular4/blob/master/LICENSE) without warranty.

**Comment by LastTribunal** [comment]
It's better to not write any code, than to write garbage code, in the arena of public consumption.  just because some one put work into something, it doesn't warrant a praise. You should be thankful I warned you about this POS,   Go ahead and use it..it suits you well

**Comment by benbaran** [comment]
@aciccarello - I adapted this from several sources as there was not a working library at the time for Angular 4. You are probably correct that it would be easier to implement your own library. Mostly I wanted to provide a working example, as well as a tutorial on creating a NPM package - neither of which I could find at them time.

**Comment by aciccarello** [comment]
@benbaran Thanks for the reply and for sharing your work. I'll close the issue then.
