### ISSUE TITLE
Basic Usage Steps

### ISSUE THREAD

**Issue by PilotBob** [benbaran/adal-angular4#92]
Is there a list of basic usage steps? I tried to follow the sample, but my app is never going to the STS to get a login/tokin. I performed the following, what am I missing.  

This is a angular6 app:

1. INstalled the package with NPM
2. Import AdalService, AdalGuard, AdalInterceptor into my module
3. Add AdalService, AdalGuard, AdalInterceptor for HTTP_INTECEPORTS to the module providers array
4. Add AdalGaurd to the canactivate: array for all of my routes
5. Added a call to adalService.init() passing in a config object with tenant: clientid: and endpoints.

My app just errors out with a 401 when making calls to the server. 
Do I need to call login somewhere? I tried adding it to the OnInit of my app component but it didn't seem to do anything.
Why do my routes activate, is the guard not doing its thing?
Maybe my endpoint is wrong, so the Guard or interceptor assumes the api call doesn't need a token. Does the interceptor look at the endpoints to determine if it should add the token?
IDK. Thanks.

**Comment by DanaEpp** [comment]
Have you looked at the example at https://github.com/benbaran/adal-angular6-example?

**Comment by michaeltarleton** [comment]
@benbaran I wrote up some quick docs on setup since I've just implemented this. I tried to add it to your wiki but couldn't so I just added it to my fork. Let me know if it's something you want to incorporate in this project.

https://github.com/michaeltarleton/adal-angular4/wiki

**Comment by benbaran** [comment]
Sure. I think there are some parts that could be simplified, but it generally looks good. I can give you access to the wiki to update it, I think...

**Comment by benbaran** [comment]
I have added to link to the example project in the Wiki. I thing it goes through everything.
