### ISSUE TITLE
acquireToken is getting null after logged in for 1st time and it gets for subsequent requests

### ISSUE THREAD

**Issue by BKB503** [benbaran/adal-angular4#95]
I'm using acquire token functionality to get access token and get data from web api end point, but sending the request for 1st time   acquire token is getting null and after second request it is getting the acquire token and works fine.

is there any work around for this or is this the bug ?

**Comment by BKB503** [comment]
But it is not taking that long to make second request it was less than 6000 seconds and any idea when will be next release carried out? any work around mean while?

**Comment by rahulraibit** [comment]
Hi, Let me first clarify that   Default LOADFRAME_TIMEOUT: '6000' is in ms not in second. [https://github.com/AzureAD/azure-activedirectory-library-for-js/wiki/Config-authentication-context](url)
 
For solving this issue I would suggest Please use another library.

[https://www.npmjs.com/package/adal-angular5](url)

**Comment by geerzo** [comment]
v4.x of this library now support adal.js 1.0.17+

**Comment by dubcdr** [comment]
@geerzo 

So do i set `loadFrmeTimeout` in my config object like so:

```typescript
const config = {
  instance: 'https://login.microsoftonline.com/',
  tenant: 'foobar.onmicrosoft.com',
  clientId: qa_group_id,
  loadFrameTimeout: 10000,
  endpoints
};
adalService.init(config);
```

**Comment by geerzo** [comment]
Hmmm, good question. I updated the library to 1.0.17 but we didn't add the additional config options. Can you do a pull request? Otherwise I'll try to get to it as I can.
